#!/usr/bin/env perl
use strict;
use warnings;

use CGI::Fast qw(:standard);
use CGI::Carp qw(fatalsToBrowser);
use constant CUSTOM_PERMLINK => 0;
use constant DBFILE => 'url.db';

use Digest::JHash qw(jhash);
use MIME::Base64 qw(encode_base64);
use DB_File;

sub error($);
my %db;

tie %db, 'DB_File', DBFILE;


while (CGI::Fast->new)
{
    my $id = path_info;
    warn "id: '$id'";
    $id =~ s|^/||;

    if (request_method eq 'POST')
    {
        print header, start_html;
        my $url = param('url');

        if (CUSTOM_PERMLINK)
        {
            $id = param('id') unless $id;
        }
        
        if ($url =~ m|^https?://|)
        {
            $id = encode_base64 pack('L', Digest::JHash::jhash($url)), '' unless $id;
            $id =~ s/==$//;

            if ($db{$id})
            {
                error "id already exists";
                next;
            }

            $db{$id} = $url;
            my $url = url
            $url =~ s|/$||;
            print h1($url . '/' . $id);
            print p("base: $url, id: $id = $db{$id}");
        } else
        {
            error "invalid url";
        }
        print end_html;
    } else
    {
        use Data::Dumper;

        my $url = $db{$id};
        if ($url)
        {
            print redirect($url);
        } else
        {
            print 
            header,
            start_html,
#                pre(Dumper \%ENV),
                h1('URL to raff'),
                start_form(-method => 'POST'),
                    p('URL: ', br,
                        textfield(-name => 'url'));

            print p('ID (optional): ',br,
                         textfield(-name => 'id', -value => $id)) if CUSTOM_PERMLINK;

            print end_form,
            end_html;
        }
    }
}

sub error($)
{
    my $msg = shift;
    print h1 "Error", p $msg;   
}
